### ISSUE TITLE
Error world creation on Quilted Fabric API on Minecraft 1.19.1: NoSuchMethodError: 'net.minecraft.class_6880 net.fabricmc.fabric.api.biome.v1.BiomeSelectionContext.getBiomeRegistryEntry()'

### ISSUE THREAD

**Issue by lospejos** [kwpugh/more_gems_fabric#52]
First of all, I'm not sure is it a this mod issue, or Quilt issue, or Fabric issue, or even Minecraft 1.19.1 issue, so sorry, if I opened this issue here.

My config:
`PolyMC 1.4.1`

Minecraft `1.19.1`, instance mods:
```
cloth-config-8.0.75-fabric.jar
modmenu-4.0.5.jar
notenoughcrashes-4.1.6+1.19-fabric.jar
qfapi-4.0.0-beta.1_qsl-3.0.0-beta.2_fapi-0.58.5_mc-1.19.1.jar
```

In this case, everything is OK, Minecraft starts without issues, new world was created successfully.

When I add `MoreGems-Fabric-1.19.1-1.4.30.jar` mod and restart, Minecraft starts OK, but when I do create a new world, error comes (see full crashdump stack trace below):
`java.lang.NoSuchMethodError: 'net.minecraft.class_6880 net.fabricmc.fabric.api.biome.v1.BiomeSelectionContext.getBiomeRegistryEntry()'`

`Not Enough Crashes` mod complains about: `More Gems, Quilt Biome API` as a possible error causes.

I know that Quilt is on early stage, but without `moregems` mod it works fine, that's why I put this issue here. Sorry if I'm mistaken.

**BTW** this error also appears for `Gobber` mod (suppose for every mod involved in world generation).

Thanks.

Crash dump goes below:

```
Time: 2022-07-30 15:03:45
Description: Starting integrated server

java.lang.NoSuchMethodError: 'net.minecraft.class_6880 net.fabricmc.fabric.api.biome.v1.BiomeSelectionContext.getBiomeRegistryEntry()'
	at Not Enough Crashes deobfuscated stack trace.(1.19.1+build.4)
	at com.kwpugh.more_gems.world.GemOrePlacedFeature.lambda$netherSelector$1(GemOrePlacedFeature.java:120)
	at org.quiltmc.qsl.worldgen.biome.impl.modification.BiomeModificationImpl.finalizeWorldGen(BiomeModificationImpl.java:141)
	at net.minecraft.server.MinecraftServer.handler$zmg000$finalizeWorldGen(MinecraftServer:5297)
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer:295)
	at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer:49)
	at net.minecraft.client.MinecraftClient.method_29603(MinecraftClient:2042)
	at net.minecraft.server.MinecraftServer.startServer(MinecraftServer:264)
	at net.minecraft.client.MinecraftClient.startIntegratedServer(MinecraftClient:2042)
	at net.minecraft.server.integrated.IntegratedServerLoader.start(IntegratedServerLoader:100)
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.startServer(CreateWorldScreen:326)
	at net.minecraft.server.integrated.IntegratedServerLoader.tryLoad(IntegratedServerLoader:247)
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.createLevel(CreateWorldScreen:310)
	at net.minecraft.client.gui.screen.world.CreateWorldScreen.method_19922(CreateWorldScreen:260)
	at net.minecraft.client.gui.widget.ButtonWidget.onPress(ButtonWidget:43)
	at net.minecraft.client.gui.widget.PressableWidget.onClick(PressableWidget:16)
	at net.minecraft.client.gui.widget.ClickableWidget.mouseClicked(ClickableWidget:120)
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27)
	at net.minecraft.client.Mouse.method_1611(Mouse:94)
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:489)
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94)
	at net.minecraft.client.Mouse.method_22686(Mouse:165)
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103)
	at net.minecraft.client.Mouse.method_22684(Mouse:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem:222)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1207)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:767)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$zbc000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:3008)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:789)
	at net.minecraft.client.main.Main.main(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.kwpugh.more_gems.world.GemOrePlacedFeature.lambda$netherSelector$1(GemOrePlacedFeature.java:120)
	at org.quiltmc.qsl.worldgen.biome.impl.modification.BiomeModificationImpl.finalizeWorldGen(BiomeModificationImpl.java:141)
	at net.minecraft.server.MinecraftServer.handler$zmg000$finalizeWorldGen(MinecraftServer.java:5297)
	at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:295)
	at net.minecraft.class_1132.<init>(class_1132.java:49)
	at net.minecraft.class_310.method_29603(class_310.java:2042)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:264)
	at net.minecraft.class_310.method_29610(class_310.java:2042)
	at net.minecraft.class_7196.method_41889(class_7196.java:100)
	at net.minecraft.class_525.method_41847(class_525.java:326)
	at net.minecraft.class_7196.method_41892(class_7196.java:247)
	at net.minecraft.class_525.method_2736(class_525.java:310)
	at net.minecraft.class_525.method_19922(class_525.java:260)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Starting integrated server --
Details:
	Level ID: with_more_gems_mod
	Level Name: with_more_gems_mod
Stacktrace:
	at net.minecraft.class_310.method_29610(class_310.java:2042)
	at net.minecraft.class_7196.method_41889(class_7196.java:100)
	at net.minecraft.class_525.method_41847(class_525.java:326)
	at net.minecraft.class_7196.method_41892(class_7196.java:247)
	at net.minecraft.class_525.method_2736(class_525.java:310)
	at net.minecraft.class_525.method_19922(class_525.java:260)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1207)
	at net.minecraft.class_310.method_1514(class_310.java:767)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$zbc000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:3008)
	at net.minecraft.class_310.method_1514(class_310.java:789)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_525
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1207)
	at net.minecraft.class_310.method_1514(class_310.java:767)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$zbc000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:3008)
	at net.minecraft.class_310.method_1514(class_310.java:789)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2345)
	at net.minecraft.class_310.method_1514(class_310.java:786)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.class_310.modify$zbc000$atTheEndOfFirstCatchBeforePrintingCrashReport(class_310.java:3008)
	at net.minecraft.class_310.method_1514(class_310.java:789)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:423)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:76)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.polymc.EntryPoint.listen(EntryPoint.java:144)
	at org.polymc.EntryPoint.main(EntryPoint.java:74)

-- System Details --
Details:
	Minecraft Version: 1.19.1
	Minecraft Version ID: 1.19.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 18.0.2, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 778061912 bytes (742 MiB) / 1398800384 bytes (1334 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900HX with Radeon Graphics        
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.29
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3080 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x249c
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6179
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x1638
	Graphics card #1 versionInfo: DriverVersion=30.0.13025.1000
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 34156.06
	Virtual memory used (MB): 16183.59
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 23.00
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Quilted Fabric API: !! WARNING !! This instance is using Fabric API modules re-implemented by QSL. If the issue comes from Quilted Fabric API, DO NOT report to Fabric; report them to Quilt instead!
	Quilt Mods: 
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-config: Cloth Config v8 8.0.75
		java: OpenJDK 64-Bit Server VM 18
		minecraft: Minecraft 1.19.1
		modmenu: Mod Menu 4.0.5
		more_gems: More Gems 1.4.30
		notenoughcrashes: Not Enough Crashes 4.1.6+1.19
		pugh_tools: Pugh Tools 1.3.15
		quilt_advancement: Quilt Advancement API 3.0.0-beta.2+1.19.1
		quilt_base: Quilt Base API 3.0.0-beta.2+1.19.1
		quilt_biome: Quilt Biome API 3.0.0-beta.2+1.19.1
		quilt_block_entity: Quilt Block Entity API 3.0.0-beta.2+1.19.1
		quilt_block_extensions: Quilt Block Extensions API 3.0.0-beta.2+1.19.1
		quilt_client_command: Quilt Client Command API 3.0.0-beta.2+1.19.1
		quilt_command: Quilt Command API 3.0.0-beta.2+1.19.1
		quilt_crash_info: Quilt Crash Info 3.0.0-beta.2+1.19.1
		quilt_dimension: Quilt Dimension API 3.0.0-beta.2+1.19.1
		quilt_item_content_registry: Quilt Item Content Registry API 3.0.0-beta.2+1.19.1
		quilt_item_group: Quilt Item Group API 3.0.0-beta.2+1.19.1
		quilt_item_setting: Quilt Item Setting API 3.0.0-beta.2+1.19.1
		quilt_lifecycle_events: Quilt Lifecycle Events 3.0.0-beta.2+1.19.1
		quilt_loader: Quilt Loader 0.17.2-beta.1
		quilt_networking: Quilt Networking 3.0.0-beta.2+1.19.1
		quilt_recipe: Quilt Recipe API 3.0.0-beta.2+1.19.1
		quilt_registry: Quilt Registry API 3.0.0-beta.2+1.19.1
		quilt_registry_entry_attachments: Quilt Registry Entry Attachments 3.0.0-beta.2+1.19.1
		quilt_resource_loader: Quilt Resource Loader 3.0.0-beta.2+1.19.1
		quilt_screen: Quilt Screen API 3.0.0-beta.2+1.19.1
		quilt_tags: Quilt Tags API 3.0.0-beta.2+1.19.1
		quilt_tooltip: Quilt Tooltip API 3.0.0-beta.2+1.19.1
		quilted_fabric_api: Quilted Fabric API 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_api_base: Quilted Fabric API Base 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_api_lookup_api_v1: Quilted Fabric API Lookup API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_biome_api_v1: Quilted Fabric Biome API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_blockrenderlayer_v1: Quilted Fabric BlockRenderLayer Registration (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_command_api_v1: Quilted Fabric Command API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_command_api_v2: Quilted Fabric Command API (v2) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_commands_v0: Quilted Fabric Commands (v0) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_containers_v0: Quilted Fabric Containers (v0) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_content_registries_v0: Quilted Fabric Content Registries (v0) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_convention_tags_api_v1: Quilted Fabric Convention Tags API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_crash_report_info_v1: Quilted Fabric Crash Report Info (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_data_generation_api_v1: Quilted Fabric Data Generation API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_dimensions_v1: Quilted Fabric Dimensions API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_entity_events_v1: Quilted Fabric Entity Events (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_events_interaction_v0: Quilted Fabric Events Interaction (v0) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_events_lifecycle_v0: Quilted Fabric Events Lifecycle (v0) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_game_rule_api_v1: Quilted Fabric Game Rule API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_item_api_v1: Quilted Fabric Item API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_item_groups_v0: Quilted Fabric Item Groups (v0) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_key_binding_api_v1: Quilted Fabric Key Binding API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_keybindings_v0: Quilted Fabric Key Bindings (v0) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_lifecycle_events_v1: Quilted Fabric Lifecycle Events (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_loot_api_v2: Quilted Fabric Loot API (v2) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_loot_tables_v1: Quilted Fabric Loot Tables (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_message_api_v1: Quilted Fabric Message API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_mining_level_api_v1: Quilted Fabric Mining Level API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_models_v0: Quilted Fabric Models (v0) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_networking_api_v1: Quilted Fabric Networking API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_networking_v0: Quilted Fabric Networking (v0) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_object_builder_api_v1: Quilted Fabric Object Builder API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_particles_v1: Quilted Fabric Particles (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_registry_sync_v0: Quilted Fabric Registry Sync (v0) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_renderer_api_v1: Quilted Fabric Renderer API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_renderer_indigo: Quilted Fabric Renderer - Indigo 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_renderer_registries_v1: Quilted Fabric Renderer Registries (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_rendering_data_attachment_v1: Quilted Fabric Rendering Data Attachment (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_rendering_fluids_v1: Quilted Fabric Rendering Fluids (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_rendering_v0: Quilted Fabric Rendering (v0) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_rendering_v1: Quilted Fabric Rendering (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_resource_conditions_api_v1: Quilted Fabric Resource Conditions API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_resource_loader_v0: Quilted Fabric Resource Loader (v0) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_screen_api_v1: Quilted Fabric Screen API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_screen_handler_api_v1: Quilted Fabric Screen Handler API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_textures_v0: Quilted Fabric Textures (v0) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_transfer_api_v1: Quilted Fabric Transfer API (v1) 4.0.0-beta.1+0.58.5-1.19.1
		quilted_fabric_transitive_access_wideners_v1: Quilted Fabric Transitive Access Wideners (v1) 4.0.0-beta.1+0.58.5-1.19.1
	Launched Version: 1.19.1
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: GeForce RTX 3080 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 461.79, NVIDIA Corporation
	Window size: 1920x1200
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: id=1280, source=API, type=ERROR, severity=HIGH, message='GL_INVALID_ENUM error generated. Polygon modes for <face> are disabled in the current profile.' x 2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'quilt'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla
	Current Language: English (US)
	CPU: 16x AMD Ryzen 9 5900HX with Radeon Graphics 
	Client Crashes Since Restart: 2
	Integrated Server Crashes Since Restart: 0
	Suspected Mods: Not Enough Crashes (notenoughcrashes), More Gems (more_gems), Quilt Loader (quilt_loader), Quilt Biome API (quilt_biome), Minecraft (minecraft)
```

**Comment by kwpugh** [comment]
there seems to be some naming differences causing a the following code to resolve:

''    public static Predicate<BiomeSelectionContext> netherSelector()
    {
        return context -> context.getBiomeRegistryEntry().isIn(BiomeTags.IS_NETHER);
    }
''

I'm not currently supporting quilt, so if my fabric mods work in quilt, great, if they don't, you are out of luck.

**Comment by lospejos** [comment]
Thanks for a quick response!

**Comment by lospejos** [comment]
For the benefit of others, I've created a linked issue in Quilted Fabric API repository: https://github.com/QuiltMC/quilted-fabric-api/issues/27
